mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tabs/', include('tabs.urls')),
    path('admin/', admin.site.urls),
]

mysite/tabs/urls.py
from django.urls import path

from . import views

app_name = 'tabs'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/tabs/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

mysite/tabs/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse

from .models import Question


# Create your views here.
def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	context = {'latest_question_list': latest_question_list,}
	return render(request, 'tabs/index.html', context)
	# Leave the rest of the views (detail, results, vote) unchanged

def detail(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'tabs/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

mysite/tabs/templates/tabs/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

mysite/tabs/templates/tabs/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li>
        	<a href="{% url 'tabs:detail' question.id %}">{{question.question_text }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}